# Generated by Django 3.2.8 on 2021-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.CreateModel(
            name='EventCustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('date', 'Date'), ('choice', 'Choice')], max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
    ]
