# Generated by Django 3.2.8 on 2021-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211025_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='eventcustomfields',
            name='field_configuration',
            field=models.JSONField(default=dict),
        ),
    ]
