# Generated by Django 3.2.8 on 2021-10-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
                ('display_name', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_value', models.CharField(max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('date', 'Date'), ('choice', 'Choice')], max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='events.event')),
            ],
        ),
    ]
